version: '3'
services:
  sftp:
    image: "${IMAGE_REPOSITORY}/sftp:${IMAGE_TAG:-latest}"
    build:
      context: .
    depends_on:
      - wait
    restart: on-failure
    privileged: true
    ports:
      - "2222:22"
    cap_add:
      - SYS_MODULE
    # If no values are provided then the default values will be set to localstack
    # environment:
      # AWS_ACCESS_KEY_ID: your-access-key-id
      # AWS_SECRET_ACCESS_KEY: your-secret-access-key
      # AWS_REGION: your-region
      # PLATFORM__BUCKET__NAME: your-bucket-name
      # PLATFORM__BUCKET__FEATURE_SET: optional-feature-set
  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
    environment:
      TARGETS: "localstack:4572"
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: s3:4572,sqs:4576
      DEBUG: s3
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
    ports:
      - "4572:4572"
      - "4576:4576"
      # PORT_WEB_UI
      - "8080"
